### ISSUE TITLE
HttpRequestTimeoutException

### ISSUE THREAD

**Issue by jordan-da** [zzehring/intellij-jsonnet#59]
This error happens when I install the plugin, any idea what it could mean?

```
io.ktor.client.plugins.HttpRequestTimeoutException: Request timeout has expired [url=https://objects.githubusercontent.com/github-production-release-asset-2e65be/437639151/06720617-e599-4fcf-b4da-3c1d5119f0e3?{LOTS OF POTENTIALLY PRIVATE STUFF} request_timeout=unknown ms]
	at io.ktor.client.engine.cio.EndpointKt$setupTimeout$timeoutJob$1.invokeSuspend(Endpoint.kt:252)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by jordan-da** [comment]
Seems to be having trouble downloading the jsonnet lang server, perhaps this is related / wrong?

![Screenshot 2023-05-23 at 12 21 54 PM](https://github.com/zzehring/intellij-jsonnet/assets/31041063/48eed7c1-4856-4115-80b0-d8483eb3f340)
